/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.28
 * Generated at: 2024-09-27 05:11:17 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.main;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class main_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(3);
    _jspx_dependants.put("/WEB-INF/lib/jakarta.servlet.jsp.jstl-2.0.0.jar", Long.valueOf(1727241247911L));
    _jspx_dependants.put("jar:file:/D:/psw_git/kh_academy/jsp/workspace/.metadata/.plugins/org.eclipse.wst.server.core/tmp8/wtpwebapps/jspproject/WEB-INF/lib/jakarta.servlet.jsp.jstl-2.0.0.jar!/META-INF/fn.tld", Long.valueOf(1602841572000L));
    _jspx_dependants.put("jar:file:/D:/psw_git/kh_academy/jsp/workspace/.metadata/.plugins/org.eclipse.wst.server.core/tmp8/wtpwebapps/jspproject/WEB-INF/lib/jakarta.servlet.jsp.jstl-2.0.0.jar!/META-INF/c.tld", Long.valueOf(1602841572000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    <title>Document</title>\r\n");
      out.write("    <script src=\"https://code.jquery.com/jquery-3.6.0.min.js\"></script>\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"../main/css_main.css\" />    \r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("    <div>\r\n");
      out.write("        <header class=\"header\"></header>\r\n");
      out.write("    </div>\r\n");
      out.write("    <!-- 테스트 용 -->\r\n");
      out.write("    <div>\r\n");
      out.write("        <h2 class=\"BOtitle\">박스오피스 순위</h2>\r\n");
      out.write("        <!-- BOcontainer -->\r\n");
      out.write("        <div class=\"BOcontatiner\">\r\n");
      out.write("            <!-- 영화 1 -->\r\n");
      out.write("             <div class=\"movie\">\r\n");
      out.write("                <!-- 포스터 주소 들어갈거임 -->\r\n");
      out.write("                 <div class=\"contents-wrap\">\r\n");
      out.write("                     <a href=\"sendMovieName\">\r\n");
      out.write("                        <img src=\"../main/testposter.png\" alt=\"베테랑2\">\r\n");
      out.write("                        <div class=\"ranking\">1</div>\r\n");
      out.write("                     </a>\r\n");
      out.write("                 </div>\r\n");
      out.write("                <div class=\"movie-info\">\r\n");
      out.write("                    <h2>영화 제목</h2>\r\n");
      out.write("                    <p>개봉일</p>\r\n");
      out.write("                </div>\r\n");
      out.write("             </div>\r\n");
      out.write("             <!-- 영화 2 -->\r\n");
      out.write("             <div class=\"movie\">\r\n");
      out.write("                <!-- 포스터 주소 들어갈거임 -->\r\n");
      out.write("                 <div class=\"contents-wrap\">\r\n");
      out.write("                     <a href=\"sendMovieName\">\r\n");
      out.write("                        <img src=\"../main/testposter.png\" alt=\"베테랑2\">\r\n");
      out.write("                        <div class=\"ranking\">1</div>\r\n");
      out.write("                     </a>\r\n");
      out.write("                 </div>\r\n");
      out.write("                <div class=\"movie-info\">\r\n");
      out.write("                    <h2>영화 제목</h2>\r\n");
      out.write("                    <p>개봉일</p>\r\n");
      out.write("                </div>\r\n");
      out.write("             </div>\r\n");
      out.write("             <!-- 영화 3 -->\r\n");
      out.write("             <div class=\"movie\">\r\n");
      out.write("                <!-- 포스터 주소 들어갈거임 -->\r\n");
      out.write("                 <div class=\"contents-wrap\">\r\n");
      out.write("                     <a href=\"sendMovieName\">\r\n");
      out.write("                        <img src=\"../main/testposter.png\" alt=\"베테랑2\">\r\n");
      out.write("                        <div class=\"ranking\">1</div>\r\n");
      out.write("                     </a>\r\n");
      out.write("                 </div>\r\n");
      out.write("                <div class=\"movie-info\">\r\n");
      out.write("                    <h2>영화 제목</h2>\r\n");
      out.write("                    <p>개봉일</p>\r\n");
      out.write("                </div>\r\n");
      out.write("             </div>\r\n");
      out.write("             <!-- 영화 4 -->\r\n");
      out.write("             <div class=\"movie\">\r\n");
      out.write("                <!-- 포스터 주소 들어갈거임 -->\r\n");
      out.write("                 <div class=\"contents-wrap\">\r\n");
      out.write("                     <a href=\"sendMovieName\">\r\n");
      out.write("                        <img src=\"../main/testposter.png\" alt=\"베테랑2\">\r\n");
      out.write("                        <div class=\"ranking\">1</div>\r\n");
      out.write("                     </a>\r\n");
      out.write("                 </div>\r\n");
      out.write("                <div class=\"movie-info\">\r\n");
      out.write("                    <h2>영화 제목</h2>\r\n");
      out.write("                    <p>개봉일</p>\r\n");
      out.write("                </div>\r\n");
      out.write("             </div>\r\n");
      out.write("             <!-- 영화 5 -->\r\n");
      out.write("             <div class=\"movie\">\r\n");
      out.write("                <!-- 포스터 주소 들어갈거임 -->\r\n");
      out.write("                 <div class=\"contents-wrap\">\r\n");
      out.write("                     <a href=\"sendMovieName\">\r\n");
      out.write("                        <img src=\"../main/testposter.png\" alt=\"베테랑2\">\r\n");
      out.write("                        <div class=\"ranking\">1</div>\r\n");
      out.write("                     </a>\r\n");
      out.write("                 </div>\r\n");
      out.write("                <div class=\"movie-info\">\r\n");
      out.write("                    <h2>영화 제목</h2>\r\n");
      out.write("                    <p>개봉일</p>\r\n");
      out.write("                </div>\r\n");
      out.write("             </div>\r\n");
      out.write("             <!-- 영화 6 -->\r\n");
      out.write("             <div class=\"movie\">\r\n");
      out.write("                <!-- 포스터 주소 들어갈거임 -->\r\n");
      out.write("                 <div class=\"contents-wrap\">\r\n");
      out.write("                     <a href=\"sendMovieName\">\r\n");
      out.write("                        <img src=\"../main/testposter.png\" alt=\"베테랑2\">\r\n");
      out.write("                        <div class=\"ranking\">1</div>\r\n");
      out.write("                     </a>\r\n");
      out.write("                 </div>\r\n");
      out.write("                <div class=\"movie-info\">\r\n");
      out.write("                    <h2>영화 제목</h2>\r\n");
      out.write("                    <p>개봉일</p>\r\n");
      out.write("                </div>\r\n");
      out.write("             </div>\r\n");
      out.write("             <!-- 영화 7 -->\r\n");
      out.write("             <div class=\"movie\">\r\n");
      out.write("                <!-- 포스터 주소 들어갈거임 -->\r\n");
      out.write("                 <div class=\"contents-wrap\">\r\n");
      out.write("                     <a href=\"sendMovieName\">\r\n");
      out.write("                        <img src=\"../main/testposter.png\" alt=\"베테랑2\">\r\n");
      out.write("                        <div class=\"ranking\">1</div>\r\n");
      out.write("                     </a>\r\n");
      out.write("                 </div>\r\n");
      out.write("                <div class=\"movie-info\">\r\n");
      out.write("                    <h2>영화 제목</h2>\r\n");
      out.write("                    <p>개봉일</p>\r\n");
      out.write("                </div>\r\n");
      out.write("             </div>\r\n");
      out.write("             <!-- 영화 8 -->\r\n");
      out.write("             <div class=\"movie\">\r\n");
      out.write("                <!-- 포스터 주소 들어갈거임 -->\r\n");
      out.write("                 <div class=\"contents-wrap\">\r\n");
      out.write("                     <a href=\"sendMovieName\">\r\n");
      out.write("                        <img src=\"../main/testposter.png\" alt=\"베테랑2\">\r\n");
      out.write("                        <div class=\"ranking\">1</div>\r\n");
      out.write("                     </a>\r\n");
      out.write("                 </div>\r\n");
      out.write("                <div class=\"movie-info\">\r\n");
      out.write("                    <h2>영화 제목</h2>\r\n");
      out.write("                    <p>개봉일</p>\r\n");
      out.write("                </div>\r\n");
      out.write("             </div>\r\n");
      out.write("             <!-- 영화 9 -->\r\n");
      out.write("             <div class=\"movie\">\r\n");
      out.write("                <!-- 포스터 주소 들어갈거임 -->\r\n");
      out.write("                 <div class=\"contents-wrap\">\r\n");
      out.write("                     <a href=\"sendMovieName\">\r\n");
      out.write("                        <img src=\"../main/testposter.png\" alt=\"베테랑2\">\r\n");
      out.write("                        <div class=\"ranking\">1</div>\r\n");
      out.write("                     </a>\r\n");
      out.write("                 </div>\r\n");
      out.write("                <div class=\"movie-info\">\r\n");
      out.write("                    <h2>영화 제목</h2>\r\n");
      out.write("                    <p>개봉일</p>\r\n");
      out.write("                </div>\r\n");
      out.write("             </div>\r\n");
      out.write("             <!-- 영화 10 -->\r\n");
      out.write("             <div class=\"movie\">\r\n");
      out.write("                <!-- 포스터 주소 들어갈거임 -->\r\n");
      out.write("                 <div class=\"contents-wrap\">\r\n");
      out.write("                     <a href=\"sendMovieName\">\r\n");
      out.write("                        <img src=\"../main/testposter.png\" alt=\"베테랑2\">\r\n");
      out.write("                        <div class=\"ranking\">1</div>\r\n");
      out.write("                     </a>\r\n");
      out.write("                 </div>\r\n");
      out.write("                <div class=\"movie-info\">\r\n");
      out.write("                    <h2>영화 제목</h2>\r\n");
      out.write("                    <p>개봉일</p>\r\n");
      out.write("                </div>\r\n");
      out.write("             </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <!-- 테스트 용 -->\r\n");
      out.write("    <div>\r\n");
      out.write("        <h2 class=\"BOtitle\">박스오피스 순위</h2>\r\n");
      out.write("        <!-- BOcontainer -->\r\n");
      out.write("        <div class=\"BOcontatiner\">\r\n");
      out.write("            <!-- 영화 1 -->\r\n");
      out.write("             <div class=\"movie\">\r\n");
      out.write("                <!-- 포스터 주소 들어갈거임 -->\r\n");
      out.write("                 <div class=\"contents-wrap\">\r\n");
      out.write("                     <a href=\"sendMovieName\">\r\n");
      out.write("                        <img src=\"../main/testposter.png\" alt=\"베테랑2\">\r\n");
      out.write("                        <div class=\"ranking\">1</div>\r\n");
      out.write("                     </a>\r\n");
      out.write("                 </div>\r\n");
      out.write("                <div class=\"movie-info\">\r\n");
      out.write("                    <h2>영화 제목</h2>\r\n");
      out.write("                    <p>개봉일</p>\r\n");
      out.write("                </div>\r\n");
      out.write("             </div>\r\n");
      out.write("             <!-- 영화 2 -->\r\n");
      out.write("             <div class=\"movie\">\r\n");
      out.write("                <!-- 포스터 주소 들어갈거임 -->\r\n");
      out.write("                 <div class=\"contents-wrap\">\r\n");
      out.write("                     <a href=\"sendMovieName\">\r\n");
      out.write("                        <img src=\"../main/testposter.png\" alt=\"베테랑2\">\r\n");
      out.write("                        <div class=\"ranking\">1</div>\r\n");
      out.write("                     </a>\r\n");
      out.write("                 </div>\r\n");
      out.write("                <div class=\"movie-info\">\r\n");
      out.write("                    <h2>영화 제목</h2>\r\n");
      out.write("                    <p>개봉일</p>\r\n");
      out.write("                </div>\r\n");
      out.write("             </div>\r\n");
      out.write("             <!-- 영화 3 -->\r\n");
      out.write("             <div class=\"movie\">\r\n");
      out.write("                <!-- 포스터 주소 들어갈거임 -->\r\n");
      out.write("                 <div class=\"contents-wrap\">\r\n");
      out.write("                     <a href=\"sendMovieName\">\r\n");
      out.write("                        <img src=\"../main/testposter.png\" alt=\"베테랑2\">\r\n");
      out.write("                        <div class=\"ranking\">1</div>\r\n");
      out.write("                     </a>\r\n");
      out.write("                 </div>\r\n");
      out.write("                <div class=\"movie-info\">\r\n");
      out.write("                    <h2>영화 제목</h2>\r\n");
      out.write("                    <p>개봉일</p>\r\n");
      out.write("                </div>\r\n");
      out.write("             </div>\r\n");
      out.write("             <!-- 영화 4 -->\r\n");
      out.write("             <div class=\"movie\">\r\n");
      out.write("                <!-- 포스터 주소 들어갈거임 -->\r\n");
      out.write("                 <div class=\"contents-wrap\">\r\n");
      out.write("                     <a href=\"sendMovieName\">\r\n");
      out.write("                        <img src=\"../main/testposter.png\" alt=\"베테랑2\">\r\n");
      out.write("                        <div class=\"ranking\">1</div>\r\n");
      out.write("                     </a>\r\n");
      out.write("                 </div>\r\n");
      out.write("                <div class=\"movie-info\">\r\n");
      out.write("                    <h2>영화 제목</h2>\r\n");
      out.write("                    <p>개봉일</p>\r\n");
      out.write("                </div>\r\n");
      out.write("             </div>\r\n");
      out.write("             <!-- 영화 5 -->\r\n");
      out.write("             <div class=\"movie\">\r\n");
      out.write("                <!-- 포스터 주소 들어갈거임 -->\r\n");
      out.write("                 <div class=\"contents-wrap\">\r\n");
      out.write("                     <a href=\"sendMovieName\">\r\n");
      out.write("                        <img src=\"../main/testposter.png\" alt=\"베테랑2\">\r\n");
      out.write("                        <div class=\"ranking\">1</div>\r\n");
      out.write("                     </a>\r\n");
      out.write("                 </div>\r\n");
      out.write("                <div class=\"movie-info\">\r\n");
      out.write("                    <h2>영화 제목</h2>\r\n");
      out.write("                    <p>개봉일</p>\r\n");
      out.write("                </div>\r\n");
      out.write("             </div>\r\n");
      out.write("             <!-- 영화 6 -->\r\n");
      out.write("             <div class=\"movie\">\r\n");
      out.write("                <!-- 포스터 주소 들어갈거임 -->\r\n");
      out.write("                 <div class=\"contents-wrap\">\r\n");
      out.write("                     <a href=\"sendMovieName\">\r\n");
      out.write("                        <img src=\"../main/testposter.png\" alt=\"베테랑2\">\r\n");
      out.write("                        <div class=\"ranking\">1</div>\r\n");
      out.write("                     </a>\r\n");
      out.write("                 </div>\r\n");
      out.write("                <div class=\"movie-info\">\r\n");
      out.write("                    <h2>영화 제목</h2>\r\n");
      out.write("                    <p>개봉일</p>\r\n");
      out.write("                </div>\r\n");
      out.write("             </div>\r\n");
      out.write("             <!-- 영화 7 -->\r\n");
      out.write("             <div class=\"movie\">\r\n");
      out.write("                <!-- 포스터 주소 들어갈거임 -->\r\n");
      out.write("                 <div class=\"contents-wrap\">\r\n");
      out.write("                     <a href=\"sendMovieName\">\r\n");
      out.write("                        <img src=\"../main/testposter.png\" alt=\"베테랑2\">\r\n");
      out.write("                        <div class=\"ranking\">1</div>\r\n");
      out.write("                     </a>\r\n");
      out.write("                 </div>\r\n");
      out.write("                <div class=\"movie-info\">\r\n");
      out.write("                    <h2>영화 제목</h2>\r\n");
      out.write("                    <p>개봉일</p>\r\n");
      out.write("                </div>\r\n");
      out.write("             </div>\r\n");
      out.write("             <!-- 영화 8 -->\r\n");
      out.write("             <div class=\"movie\">\r\n");
      out.write("                <!-- 포스터 주소 들어갈거임 -->\r\n");
      out.write("                 <div class=\"contents-wrap\">\r\n");
      out.write("                     <a href=\"sendMovieName\">\r\n");
      out.write("                        <img src=\"../main/testposter.png\" alt=\"베테랑2\">\r\n");
      out.write("                        <div class=\"ranking\">1</div>\r\n");
      out.write("                     </a>\r\n");
      out.write("                 </div>\r\n");
      out.write("                <div class=\"movie-info\">\r\n");
      out.write("                    <h2>영화 제목</h2>\r\n");
      out.write("                    <p>개봉일</p>\r\n");
      out.write("                </div>\r\n");
      out.write("             </div>\r\n");
      out.write("             <!-- 영화 9 -->\r\n");
      out.write("             <div class=\"movie\">\r\n");
      out.write("                <!-- 포스터 주소 들어갈거임 -->\r\n");
      out.write("                 <div class=\"contents-wrap\">\r\n");
      out.write("                     <a href=\"sendMovieName\">\r\n");
      out.write("                        <img src=\"../main/testposter.png\" alt=\"베테랑2\">\r\n");
      out.write("                        <div class=\"ranking\">1</div>\r\n");
      out.write("                     </a>\r\n");
      out.write("                 </div>\r\n");
      out.write("                <div class=\"movie-info\">\r\n");
      out.write("                    <h2>영화 제목</h2>\r\n");
      out.write("                    <p>개봉일</p>\r\n");
      out.write("                </div>\r\n");
      out.write("             </div>\r\n");
      out.write("             <!-- 영화 10 -->\r\n");
      out.write("             <div class=\"movie\">\r\n");
      out.write("                <!-- 포스터 주소 들어갈거임 -->\r\n");
      out.write("                 <div class=\"contents-wrap\">\r\n");
      out.write("                     <a href=\"sendMovieName\">\r\n");
      out.write("                        <img src=\"../main/testposter.png\" alt=\"베테랑2\">\r\n");
      out.write("                        <div class=\"ranking\">1</div>\r\n");
      out.write("                     </a>\r\n");
      out.write("                 </div>\r\n");
      out.write("                <div class=\"movie-info\">\r\n");
      out.write("                    <h2>영화 제목</h2>\r\n");
      out.write("                    <p>개봉일</p>\r\n");
      out.write("                </div>\r\n");
      out.write("             </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        \r\n");
      out.write("    </div>\r\n");
      out.write("    <div>\r\n");
      out.write("        <footer class=\"footer\"></footer>\r\n");
      out.write("    </div>\r\n");
      out.write("    <script>\r\n");
      out.write("        $(function(){\r\n");
      out.write("            $(\".header\").load(\"../header/header.html\");\r\n");
      out.write("            $(\".footer\").load(\"../footer/footer.html\");\r\n");
      out.write("        });\r\n");
      out.write("    </script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
